services:
  backend:
    container_name: backend-container
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    depends_on:
      - database
    networks:
      - backend-database-network

  webserver:
    restart: always
    container_name: webserver-container
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - frontend-volume:/var/www/frontend
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
      - database
    networks:
      - backend-database-network

  frontend:
    container_name: frontend-container
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/frontend
      - frontend-volume:/frontend/frontend/build
    ports:
      - "3000:3000"

  database:
    container_name: database-container
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: backenddb
      MYSQL_USER: user
      MSQL_PASSWORD: user
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - "3306:3306"
    networks:
      - backend-database-network
    volumes:
      - ./database/sql:/docker-entrypoint-initdb.d

volumes:
  frontend-volume:

networks:
  backend-database-network:
    driver: bridge