apiVersion: batch/v1
kind: Job
metadata:
  name: backend-job
spec:
  template:
    spec:
      containers:
      - name: backend-job-container
        image: isatoshi/django-react-nginx-mysql-backend
        # command: ["sh", "-c", "/backend/entrypoint.sh"]
      restartPolicy: Never