apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      component: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: backend
    spec:
      containers:
        - image: isatoshi/django-react-nginx-mysql-backend
          name: backend-container
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE
              valueFrom:
                configMapKeyRef:
                  name: app-variables
                  key: DATABASE
            - name: DB_ENGINE
              valueFrom:
                configMapKeyRef:
                  name: app-variables
                  key: DB_ENGINE
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: app-variables
                  key: DB_DATABASE
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: app-variables
                  key: DB_USER
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-variables
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-variables
                  key: DB_PORT
            - name: DJANGO_ALLOWED_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: app-variables
                  key: DJANGO_ALLOWED_HOSTS
            - name: DJANGO_ADMIN_USER
              valueFrom:
                configMapKeyRef:
                  name: app-variables
                  key: DJANGO_ADMIN_USER 
            - name: DJANGO_ADMIN_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: app-variables
                  key: DJANGO_ADMIN_PASSWORD 
            - name: DJANGO_ADMIN_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: app-variables
                  key: DJANGO_ADMIN_EMAIL
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "2048Mi"
              cpu: "1000m"
      # restartPolicy: Always
status: {}
