apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\user\AppData\Local\Microsoft\WinGet\Links\kompose.exe --file .\docker-compose.yaml convert
    kompose.version: 1.30.0 (9d8dcb518)
  labels:
    io.kompose.service: backend
  name: backend
  namespace: default
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  type: ClusterIP
  selector:
    io.kompose.service: backend
status:
  loadBalancer: {}
