apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      component: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: database
    spec:
      containers:
        - args:
            - mysqld
            - --character-set-server=utf8
            - --collation-server=utf8_unicode_ci
          env:
            - name: MYSQL_PASSWORD
              value: user
            - name: MYSQL_DATABASE
              value: backenddb
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_USER
              value: user
            - name: TZ
              value: Asia/Tokyo
          image: isatoshi/django-react-nginx-mysql-database
          name: database-container
          ports:
            - containerPort: 3306
              protocol: TCP
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: database-volume
      restartPolicy: Always
      volumes:
        - name: database-volume
          persistentVolumeClaim:
            claimName: database-volume
status: {}
