apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: default
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  type: ClusterIP
  selector:
    component: frontend
status:
  loadBalancer: {}
