apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      component: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: frontend
    spec:
      containers:
        - image: isatoshi/django-react-nginx-mysql-frontend
          name: frontend-container
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      #     volumeMounts:
      #       - mountPath: /frontend/frontend/build
      #         name: frontend-volume
      # volumes:
      #   - name: frontend-volume
      #     persistentVolumeClaim:
      #       claimName: frontend-volume
status: {}
