# Generated by Django 4.2.7 on 2023-11-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typinggame', '0002_alter_appuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('elapsed_time', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('word_length', models.PositiveIntegerField()),
            ],
        ),
    ]
