# Generated by Django 4.2.7 on 2023-11-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typinggame', '0003_userrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecord',
            name='elapsed_time',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
