# Generated by Django 4.2.7 on 2023-11-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typinggame', '0004_alter_userrecord_elapsed_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecord',
            name='elapsed_time',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
